kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:8.14.2-jdk21-jammy
    commands:
      - export BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - apt-get update && apt-get install -y p7zip-full unrar git-restore-mtime
      - git restore-mtime ./www/src/main/resources/
      - gradle --no-daemon test

  - name: publish
    image: gradle:8.14.2-jdk21-jammy
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - export BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - apt-get update && apt-get install -y git-restore-mtime
      - git restore-mtime ./www/src/main/resources/
      - gradle --no-daemon --build-cache jlinkTar publish
    when:
      ref:
        - refs/heads/master
