kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:8.1.1-jdk17-jammy
    commands:
      - apt-get update && apt-get install -y p7zip-full unrar git-restore-mtime
      - git restore-mtime ./www/src/main/resources/
      - gradle --no-daemon test

  - name: publish
    image: gradle:8.1.1-jdk17-jammy
    environment:
      BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - apt-get update && apt-get install -y git-restore-mtime
      - git restore-mtime ./www/src/main/resources/
      - gradle --no-daemon --build-cache jlinkTar publish
    when:
      ref:
        - refs/heads/master

  - name: www
    image: gradle:8.1.1-jdk17-jammy
    environment:
      DRONE_TOKEN:
        from_secret: DRONE_TOKEN
    commands:
      - echo "Triggering content rebuild"
      - |
        curl -s -X POST \
        -H "Authorization: Bearer ${DRONE_TOKEN}" \
        https://build.shrimpworks.za.net/api/repos/unreal-archive/unreal-archive-data/builds
    when:
      ref:
        - refs/heads/master
